### ISSUE TITLE
Cannot follow the configuration example, please help

### ISSUE THREAD

**Issue by Zloy** [celluloid/dcell#100]
Versions:
* zeromq-4.0.7 (also tried 4.1.2)
* ffi-rzmq-2.0.4
* ruby-2.0.0-p353
* redis-2.8.4

The example: https://github.com/celluloid/dcell/wiki/Configuration

```
2.0.0-p353 :001 > require 'dcell'
 => true 
2.0.0-p353 :002 > require 'dcell/registries/redis_adapter'
 => false 
2.0.0-p353 :003 > registry = DCell::Registry::RedisAdapter.new :server => 'localhost'
 => #<DCell::Registry::RedisAdapter:0x00000001d88e60 @env="production", @namespace="dcell_production", @redis=#<Redis::Namespace:0x00000001d888e8 @namespace="dcell_production", @redis=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>, @warning=true, @deprecations=false>, @node_registry=#<DCell::Registry::RedisAdapter::NodeRegistry:0x00000001d88870 @redis=#<Redis::Namespace:0x00000001d888e8 @namespace="dcell_production", @redis=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>, @warning=true, @deprecations=false>>, @global_registry=#<DCell::Registry::RedisAdapter::GlobalRegistry:0x00000001d88848 @redis=#<Redis::Namespace:0x00000001d888e8 @namespace="dcell_production", @redis=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>, @warning=true, @deprecations=false>>> 
2.0.0-p353 :004 > registry.set_global 'x', 12
 => false 
2.0.0-p353 :005 > registry.get_global 'x' => 12 
2.0.0-p353 :006 > registry.global_keys
 => ["x"] 
2.0.0-p353 :007 > DCell.start :registry => registry
NoMethodError: undefined method `[]' for #<DCell::Registry::RedisAdapter:0x00000001d88e60>
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:55:in `block in setup'
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:46:in `synchronize'
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:46:in `setup'
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:114:in `start'
        from (irb):7
        from /usr/local/rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'
```

**Comment by Zloy** [comment]
I cloned the repositore, checked out 0.16.1 `git checkout tags/v0.16.1` and ran tests. They passed.

I also successfully ran ffi-rzmq tests, see in the end
```
~/sources/dcell > rake
/usr/local/rvm/rubies/ruby-2.0.0-p353/bin/ruby -S rspec ./spec/dcell/actor_proxy_spec.rb ./spec/dcell/celluloid_ext_spec.rb ./spec/dcell/directory_spec.rb ./spec/dcell/explorer_spec.rb ./spec/dcell/global_spec.rb ./spec/dcell/node_spec.rb ./spec/dcell/registries/mongodb_adapter_spec.rb ./spec/dcell/registries/redis_adapter_spec.rb ./spec/dcell/registries/zk_adapter_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Waiting for test node to start up.... done!

DCell::CellProxy
I, [2015-07-07T17:14:08.743196 #27131]  INFO -- : Connected to test_node
I, [2015-07-07T17:14:08.749647 #27153]  INFO -- : Connected to 706bccb4219d5b3c93f2e04e461fb63d44bd7987e40305da00ac20db47a09a9ebb038dc7b423c2f8137cc5dacb49ec7a7f96bc817a2c071e493c03180db4dfee
  makes synchronous calls to remote actors
  handles blocks
  makes future calls to remote actors
  linking
    links to remote actors
    unlinks from remote actors
E, [2015-07-07T17:14:08.964363 #27153] ERROR -- : Actor crashed!
RuntimeError: the spec purposely crashed me :(
        /home/user/sources/dcell/spec/test_node.rb:33:in `crash'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/calls.rb:26:in `public_send'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/calls.rb:26:in `dispatch'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/calls.rb:63:in `dispatch'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/cell.rb:60:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/cell.rb:71:in `block in task'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/actor.rb:357:in `block in task'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/tasks.rb:57:in `block in initialize'
        /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/celluloid-21b8c5bd5e65/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    traps exit messages from other actors

Celluloid extensions
  marshals Celluloid::CellProxy objects
  marshals Celluloid::Mailbox objects
  marshals Celluloid::Future objects

DCell::Directory
  stores node addresses
  presents all stored addresses
  clears node addresses

DCell::Explorer
I, [2015-07-07T17:14:09.140847 #27131]  INFO -- : Connected to 706bccb4219d5b3c93f2e04e461fb63d44bd7987e40305da00ac20db47a09a9ebb038dc7b423c2f8137cc5dacb49ec7a7f96bc817a2c071e493c03180db4dfee
I, [2015-07-07T17:14:09.169774 #27131]  INFO -- : 200 OK: /index.html
  reports the current node's status

DCell::Global
  can handle unexisting keys
  stores values
  stores the keys of all globals

DCell::Node
  finds all available nodes
  finds remote actors
  lists remote actors

DCell::Registry::MongodbAdapter
  behaves like a DCell registry
    node registry
      stores node addresses (PENDING: no mongodb)
      stores the IDs of all nodes (PENDING: no mongodb)
    global registry
      stores values (PENDING: no mongodb)
      stores the keys of all globals (PENDING: no mongodb)

DCell::Registry::RedisAdapter
  behaves like a DCell registry
    node registry
      stores node addresses
      stores the IDs of all nodes
    global registry
      stores values
      stores the keys of all globals

DCell::Registry::ZkAdapter
  behaves like a DCell registry
    node registry
      stores node addresses (PENDING: no zookeeper)
      stores the IDs of all nodes (PENDING: no zookeeper)
    global registry
      stores values (PENDING: no zookeeper)
      stores the keys of all globals (PENDING: no zookeeper)
    when one znode changes
      updates a node (PENDING: no zookeeper)
    when one znode is deleted
      deletes a node (PENDING: no zookeeper)

Pending:
  DCell::Registry::MongodbAdapter behaves like a DCell registry node registry stores node addresses
    # no mongodb
    # ./spec/support/registry_examples.rb:7
  DCell::Registry::MongodbAdapter behaves like a DCell registry node registry stores the IDs of all nodes
    # no mongodb
    # ./spec/support/registry_examples.rb:14
  DCell::Registry::MongodbAdapter behaves like a DCell registry global registry stores values
    # no mongodb
    # ./spec/support/registry_examples.rb:25
  DCell::Registry::MongodbAdapter behaves like a DCell registry global registry stores the keys of all globals
    # no mongodb
    # ./spec/support/registry_examples.rb:30
  DCell::Registry::ZkAdapter behaves like a DCell registry node registry stores node addresses
    # no zookeeper
    # ./spec/support/registry_examples.rb:7
  DCell::Registry::ZkAdapter behaves like a DCell registry node registry stores the IDs of all nodes
    # no zookeeper
    # ./spec/support/registry_examples.rb:14
  DCell::Registry::ZkAdapter behaves like a DCell registry global registry stores values
    # no zookeeper
    # ./spec/support/registry_examples.rb:25
  DCell::Registry::ZkAdapter behaves like a DCell registry global registry stores the keys of all globals
    # no zookeeper
    # ./spec/support/registry_examples.rb:30
  DCell::Registry::ZkAdapter behaves like a DCell registry when one znode changes updates a node
    # no zookeeper
    # ./spec/dcell/registries/zk_adapter_spec.rb:8
  DCell::Registry::ZkAdapter behaves like a DCell registry when one znode is deleted deletes a node
    # no zookeeper
    # ./spec/dcell/registries/zk_adapter_spec.rb:18

Finished in 1.71 seconds
33 examples, 0 failures, 10 pending
D, [2015-07-07T17:14:09.309500 #27131] DEBUG -- : Terminating 18 actors...
W, [2015-07-07T17:14:09.314736 #27131]  WARN -- : Terminating task: type=:call, meta={:method_name=>:run}, status=:zmqwait
        Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
W, [2015-07-07T17:14:09.315225 #27131]  WARN -- : Terminating task: type=:call, meta={:method_name=>:run}, status=:iowait
        Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
[Coveralls] Outside the CI environment, not sending data.
~/sources/dcell > irb
2.0.0-p353 :001 > require 'dcell'                                                => true
2.0.0-p353 :002 > require 'dcell/registries/redis_adapter'                       => false
2.0.0-p353 :003 > registry = DCell::Registry::RedisAdapter.new :server => 'localhost'
 => #<DCell::Registry::RedisAdapter:0x00000002f61240 @env="production", @namespace="dcell_production", @redis=#<Redis::Namespace:0x00000002f60c50 @namespace="dcell_production", @redis=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>, @warning=true, @deprecations=false>, @node_registry=#<DCell::Registry::RedisAdapter::NodeRegistry:0x00000002f60bd8 @redis=#<Redis::Namespace:0x00000002f60c50 @namespace="dcell_production", @redis=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>, @warning=true, @deprecations=false>>, @global_registry=#<DCell::Registry::RedisAdapter::GlobalRegistry:0x00000002f60bb0 @redis=#<Redis::Namespace:0x00000002f60c50 @namespace="dcell_production", @redis=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>, @warning=true, @deprecations=false>>>
2.0.0-p353 :004 > DCell.start :registry => registry                             NoMethodError: undefined method `[]' for #<DCell::Registry::RedisAdapter:0x00000002f61240>
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:55:in `block in setup'
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:46:in `synchronize'
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:46:in `setup'
        from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/dcell-0.16.1/lib/dcell.rb:114:in `start'
        from (irb):4
        from /usr/local/rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'
2.0.0-p353 :005 >
```

ffi-rzmq test log:

```
~/sources/ffi-rzmq > git checkout tags/release-2.0.4
Note: checking out 'tags/release-2.0.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 33c1d0f... update to 2.0.3 and go into maintenance mode

~/sources/ffi-rzmq > bundle
Resolving dependencies...
Using rake (10.4.2)  
Using diff-lcs (1.2.5)
Using ffi (1.9.10)   
Using ffi-rzmq-core (1.0.3)
Using ffi-rzmq (2.1.0) from source at .
Using rspec-core (2.99.2)
Using rspec-expectations (2.99.2)
Using rspec-mocks (2.99.4)
Using rspec (2.99.0) 
Using bundler (1.3.5)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
~/sources/ffi-rzmq > rake
/usr/local/rvm/rubies/ruby-2.0.0-p353/bin/ruby -S rspec ./spec/context_spec.rb .
/spec/device_spec.rb ./spec/message_spec.rb ./spec/multipart_spec.rb ./spec/nonb
locking_recv_spec.rb ./spec/poll_spec.rb ./spec/pushpull_spec.rb ./spec/reqrep_spec.rb ./spec/socket_spec.rb ./spec/util_spec.rb
...............create streamer device and running...
broke out of wait_for_device loop
device exited
.create streamer device and running...
broke out of wait_for_device loop
device exited
...........................................................................................................................................................................................................................................................................................................................................................................................................................................
Deprecation Warnings:

Continuing to use a test double after it has been reset (e.g. in a subsequent example) is deprecated. Called from /home/zhan/sources/ffi-rzmq/lib/ffi-rzmq/socket.rb:607:in `zmq_close'.

Using rspec-mocks doubles or partial doubles outside the per-test lifecycle (such as in a `before(:all)` hook) is deprecated. Called from /home/zhan/sources/ffi-rzmq/lib/ffi-rzmq/socket.rb:607:in `zmq_close'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total

Finished in 1.92 seconds
443 examples, 0 failures
```

**Comment by Zloy** [comment]
Finally found the error in wiki, fixed it. https://github.com/celluloid/dcell/wiki/Configuration/_compare/3f36125f4738a57740a3ddf79af7168de78ce19e...f8b60d3570c174a27dd8f7455035595b07ad00a9

**Comment by niamster** [comment]
The example was for the master branch, so I'm reverting the wiki.
