### ISSUE TITLE
Zookeeper adapter

### ISSUE THREAD

**Issue by kamsz** [celluloid/dcell#46]
Documentation doesn't specify the way to use ZK adapter in DCell. After trying to specify it using:

``` ruby
require 'dcell'
require 'celluloid/io'
require 'json'
require 'socket'
 
DCell.start :id => `hostname`.chomp!, :addr => "tcp://#{IPSocket.getaddress(Socket.gethostname)}:5555",
            :registry =>
                {
                    :adapter => 'zk',
                    :host => '192.168.15.11'
                }
```

I've received exception:

```
D, [2013-05-13T09:31:50.458973 #20433] DEBUG -- : Terminating 1 actors...
D, [2013-05-13T09:31:50.460026 #20433] DEBUG -- : Shutdown completed cleanly
/var/lib/gems/1.9.1/gems/dcell-0.14.0/lib/dcell.rb:62:in `rescue in block in setup': invalid registry adapter:  (ArgumentError)
        from /var/lib/gems/1.9.1/gems/dcell-0.14.0/lib/dcell.rb:59:in `block in setup'
        from <internal:prelude>:10:in `synchronize'
        from /var/lib/gems/1.9.1/gems/dcell-0.14.0/lib/dcell.rb:45:in `setup'
        from /var/lib/gems/1.9.1/gems/dcell-0.14.0/lib/dcell.rb:101:in `start'
        from agent-zoo.rb:6:in `<main>'
```

Thanks to the @aflatter at IRC channel solution to the problem is to add requires for:
1. zk
2. dcell/registries/zk_adapter

Also :registry block looks slightly different:
``` ruby
            :registry =>
                {
                    :adapter => 'zk',
                    :server => '192.168.15.11',
                }

**Comment by niamster** [comment]
Closing this as no activity ... hope it's clear now how to use ZK registry adapter.
